// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ESP32_MQTT

#include "../ui.h"

void ui_Dashboard_screen_init(void)
{
    ui_Dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTemperature = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblTemperature, 100);
    lv_obj_set_height(ui_lblTemperature, 20);
    lv_obj_set_x(ui_lblTemperature, 5);
    lv_obj_set_y(ui_lblTemperature, 5);
    lv_label_set_text(ui_lblTemperature, "Temperature:");

    ui_lblHumidity = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblHumidity, 100);
    lv_obj_set_height(ui_lblHumidity, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lblHumidity, 5);
    lv_obj_set_y(ui_lblHumidity, 20);
    lv_label_set_text(ui_lblHumidity, "Humidity:");

    ui_lblTemperatureValue = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblTemperatureValue, 40);
    lv_obj_set_height(ui_lblTemperatureValue, 20);
    lv_obj_set_x(ui_lblTemperatureValue, 110);
    lv_obj_set_y(ui_lblTemperatureValue, 5);
    lv_label_set_text(ui_lblTemperatureValue, "0 C");

    ui_lblHumidityValue = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblHumidityValue, 40);
    lv_obj_set_height(ui_lblHumidityValue, 20);
    lv_obj_set_x(ui_lblHumidityValue, 110);
    lv_obj_set_y(ui_lblHumidityValue, 20);
    lv_label_set_text(ui_lblHumidityValue, "0 %");

}
