// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ESP32_MQTT

#include "../ui.h"

void ui_Dashboard_screen_init(void)
{
    ui_Dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Dashboard, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dashboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTemperature = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblTemperature, 150);
    lv_obj_set_height(ui_lblTemperature, 40);
    lv_obj_set_x(ui_lblTemperature, 10);
    lv_obj_set_y(ui_lblTemperature, 5);
    lv_label_set_text(ui_lblTemperature, "Temperature:");
    lv_obj_set_style_text_font(ui_lblTemperature, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHumidity = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblHumidity, 150);
    lv_obj_set_height(ui_lblHumidity, 40);
    lv_obj_set_x(ui_lblHumidity, 10);
    lv_obj_set_y(ui_lblHumidity, 40);
    lv_label_set_text(ui_lblHumidity, "Humidity:");
    lv_obj_set_style_text_font(ui_lblHumidity, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTemperatureValue = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblTemperatureValue, 60);
    lv_obj_set_height(ui_lblTemperatureValue, 40);
    lv_obj_set_x(ui_lblTemperatureValue, 170);
    lv_obj_set_y(ui_lblTemperatureValue, 5);
    lv_label_set_text(ui_lblTemperatureValue, "0 C");
    lv_obj_set_style_text_font(ui_lblTemperatureValue, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHumidityValue = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lblHumidityValue, 60);
    lv_obj_set_height(ui_lblHumidityValue, 40);
    lv_obj_set_x(ui_lblHumidityValue, 170);
    lv_obj_set_y(ui_lblHumidityValue, 40);
    lv_label_set_text(ui_lblHumidityValue, "0 %");
    lv_obj_set_style_text_font(ui_lblHumidityValue, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}
