// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ESP32_MQTT

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblConnecting = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblConnecting, 0);
    lv_obj_set_y(ui_lblConnecting, 60);
    lv_obj_set_align(ui_lblConnecting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConnecting, "Connecting with Router.....");
    lv_obj_set_style_text_color(ui_lblConnecting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblConnecting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblConnecting, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spinnerBusy = lv_spinner_create(ui_MainScreen, 1000, 90);
    lv_obj_set_width(ui_spinnerBusy, 80);
    lv_obj_set_height(ui_spinnerBusy, 80);
    lv_obj_set_x(ui_spinnerBusy, 0);
    lv_obj_set_y(ui_spinnerBusy, -10);
    lv_obj_set_align(ui_spinnerBusy, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_spinnerBusy, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_spinnerBusy, lv_color_hex(0x888686), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinnerBusy, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
