// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#include "../ui.h"

void ui_Delhi_screen_init(void)
{
    ui_Delhi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Delhi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_delhiImage = lv_img_create(ui_Delhi);
    lv_img_set_src(ui_delhiImage, &ui_img_delhi_png);
    lv_obj_set_width(ui_delhiImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delhiImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_delhiImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_delhiImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_delhiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temperature = lv_label_create(ui_Delhi);
    lv_obj_set_height(ui_Temperature, 20);
    lv_obj_set_width(ui_Temperature, lv_pct(45));
    lv_obj_set_x(ui_Temperature, -70);
    lv_obj_set_y(ui_Temperature, -100);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "Temperature: ");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pressure = lv_label_create(ui_Delhi);
    lv_obj_set_height(ui_Pressure, 20);
    lv_obj_set_width(ui_Pressure, lv_pct(45));
    lv_obj_set_x(ui_Pressure, -70);
    lv_obj_set_y(ui_Pressure, -80);
    lv_obj_set_align(ui_Pressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pressure, "Pressure:");
    lv_obj_set_style_text_color(ui_Pressure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pressure, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pressure, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValue = lv_label_create(ui_Delhi);
    lv_obj_set_height(ui_tempValue, 20);
    lv_obj_set_width(ui_tempValue, lv_pct(45));
    lv_obj_set_x(ui_tempValue, 80);
    lv_obj_set_y(ui_tempValue, -100);
    lv_obj_set_align(ui_tempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempValue, "20 C");
    lv_obj_set_style_text_color(ui_tempValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressureValue = lv_label_create(ui_Delhi);
    lv_obj_set_height(ui_pressureValue, 20);
    lv_obj_set_width(ui_pressureValue, lv_pct(45));
    lv_obj_set_x(ui_pressureValue, 80);
    lv_obj_set_y(ui_pressureValue, -80);
    lv_obj_set_align(ui_pressureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pressureValue, "1000 bar");
    lv_obj_set_style_text_color(ui_pressureValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pressureValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pressureValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pressureValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Delhi);
    lv_obj_set_height(ui_Humidity, 20);
    lv_obj_set_width(ui_Humidity, lv_pct(45));
    lv_obj_set_x(ui_Humidity, -70);
    lv_obj_set_y(ui_Humidity, -60);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "Humidity:");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityValue = lv_label_create(ui_Delhi);
    lv_obj_set_height(ui_humidityValue, 20);
    lv_obj_set_width(ui_humidityValue, lv_pct(45));
    lv_obj_set_x(ui_humidityValue, 80);
    lv_obj_set_y(ui_humidityValue, -60);
    lv_obj_set_align(ui_humidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidityValue, "80 %");
    lv_obj_set_style_text_color(ui_humidityValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidityValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humidityValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidityValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
