// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#include "../ui.h"

void ui_Leh_screen_init(void)
{
    ui_Leh = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Leh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lehImage = lv_img_create(ui_Leh);
    lv_img_set_src(ui_lehImage, &ui_img_leh_png);
    lv_obj_set_width(ui_lehImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lehImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lehImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lehImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lehImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
