// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lehImage = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_lehImage, &ui_img_leh_png);
    lv_obj_set_width(ui_lehImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lehImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lehImage, -84);
    lv_obj_set_y(ui_lehImage, 35);
    lv_obj_set_align(ui_lehImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lehImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lehImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temperature3 = lv_label_create(ui_Screen4);
    lv_obj_set_height(ui_Temperature3, 20);
    lv_obj_set_width(ui_Temperature3, lv_pct(45));
    lv_obj_set_x(ui_Temperature3, -70);
    lv_obj_set_y(ui_Temperature3, -100);
    lv_obj_set_align(ui_Temperature3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature3, "Temperature: ");
    lv_obj_set_style_text_color(ui_Temperature3, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pressure3 = lv_label_create(ui_Screen4);
    lv_obj_set_height(ui_Pressure3, 20);
    lv_obj_set_width(ui_Pressure3, lv_pct(45));
    lv_obj_set_x(ui_Pressure3, -70);
    lv_obj_set_y(ui_Pressure3, -80);
    lv_obj_set_align(ui_Pressure3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pressure3, "Pressure:");
    lv_obj_set_style_text_color(ui_Pressure3, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pressure3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pressure3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pressure3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValue3 = lv_label_create(ui_Screen4);
    lv_obj_set_height(ui_tempValue3, 20);
    lv_obj_set_width(ui_tempValue3, lv_pct(45));
    lv_obj_set_x(ui_tempValue3, 80);
    lv_obj_set_y(ui_tempValue3, -100);
    lv_obj_set_align(ui_tempValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempValue3, "20 C");
    lv_obj_set_style_text_color(ui_tempValue3, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempValue3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempValue3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressureValue3 = lv_label_create(ui_Screen4);
    lv_obj_set_height(ui_pressureValue3, 20);
    lv_obj_set_width(ui_pressureValue3, lv_pct(45));
    lv_obj_set_x(ui_pressureValue3, 80);
    lv_obj_set_y(ui_pressureValue3, -80);
    lv_obj_set_align(ui_pressureValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pressureValue3, "1000 bar");
    lv_obj_set_style_text_color(ui_pressureValue3, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pressureValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pressureValue3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pressureValue3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity3 = lv_label_create(ui_Screen4);
    lv_obj_set_height(ui_Humidity3, 20);
    lv_obj_set_width(ui_Humidity3, lv_pct(45));
    lv_obj_set_x(ui_Humidity3, -70);
    lv_obj_set_y(ui_Humidity3, -60);
    lv_obj_set_align(ui_Humidity3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity3, "Humidity:");
    lv_obj_set_style_text_color(ui_Humidity3, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityValue3 = lv_label_create(ui_Screen4);
    lv_obj_set_height(ui_humidityValue3, 20);
    lv_obj_set_width(ui_humidityValue3, lv_pct(45));
    lv_obj_set_x(ui_humidityValue3, 80);
    lv_obj_set_y(ui_humidityValue3, -60);
    lv_obj_set_align(ui_humidityValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidityValue3, "80 %");
    lv_obj_set_style_text_color(ui_humidityValue3, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidityValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humidityValue3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidityValue3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
