// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_shimlaImage = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_shimlaImage, &ui_img_shimla_png);
    lv_obj_set_width(ui_shimlaImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shimlaImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_shimlaImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shimlaImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_shimlaImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temperature1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_Temperature1, 20);
    lv_obj_set_width(ui_Temperature1, lv_pct(45));
    lv_obj_set_x(ui_Temperature1, -70);
    lv_obj_set_y(ui_Temperature1, -100);
    lv_obj_set_align(ui_Temperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature1, "Temperature: ");
    lv_obj_set_style_text_color(ui_Temperature1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pressure1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_Pressure1, 20);
    lv_obj_set_width(ui_Pressure1, lv_pct(45));
    lv_obj_set_x(ui_Pressure1, -70);
    lv_obj_set_y(ui_Pressure1, -80);
    lv_obj_set_align(ui_Pressure1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pressure1, "Pressure:");
    lv_obj_set_style_text_color(ui_Pressure1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pressure1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pressure1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pressure1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValue1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_tempValue1, 20);
    lv_obj_set_width(ui_tempValue1, lv_pct(45));
    lv_obj_set_x(ui_tempValue1, 80);
    lv_obj_set_y(ui_tempValue1, -100);
    lv_obj_set_align(ui_tempValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempValue1, "20 C");
    lv_obj_set_style_text_color(ui_tempValue1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempValue1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempValue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressureValue1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_pressureValue1, 20);
    lv_obj_set_width(ui_pressureValue1, lv_pct(45));
    lv_obj_set_x(ui_pressureValue1, 80);
    lv_obj_set_y(ui_pressureValue1, -80);
    lv_obj_set_align(ui_pressureValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pressureValue1, "1000 bar");
    lv_obj_set_style_text_color(ui_pressureValue1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pressureValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pressureValue1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pressureValue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_Humidity1, 20);
    lv_obj_set_width(ui_Humidity1, lv_pct(45));
    lv_obj_set_x(ui_Humidity1, -70);
    lv_obj_set_y(ui_Humidity1, -60);
    lv_obj_set_align(ui_Humidity1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity1, "Humidity:");
    lv_obj_set_style_text_color(ui_Humidity1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityValue1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_humidityValue1, 20);
    lv_obj_set_width(ui_humidityValue1, lv_pct(45));
    lv_obj_set_x(ui_humidityValue1, 80);
    lv_obj_set_y(ui_humidityValue1, -60);
    lv_obj_set_align(ui_humidityValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidityValue1, "80 %");
    lv_obj_set_style_text_color(ui_humidityValue1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidityValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humidityValue1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidityValue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CityName1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_CityName1, 20);
    lv_obj_set_width(ui_CityName1, lv_pct(45));
    lv_obj_set_x(ui_CityName1, -70);
    lv_obj_set_y(ui_CityName1, -40);
    lv_obj_set_align(ui_CityName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CityName1, "City Name:");
    lv_obj_set_style_text_color(ui_CityName1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CityName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CityName1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CityName1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityNameValue1 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_cityNameValue1, 20);
    lv_obj_set_width(ui_cityNameValue1, lv_pct(45));
    lv_obj_set_x(ui_cityNameValue1, 80);
    lv_obj_set_y(ui_cityNameValue1, -40);
    lv_obj_set_align(ui_cityNameValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cityNameValue1, "Shimla");
    lv_obj_set_style_text_color(ui_cityNameValue1, lv_color_hex(0xCF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cityNameValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cityNameValue1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cityNameValue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
