// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef _ESP32_TRAFFICCONTROLLER_UI_H
#define _ESP32_TRAFFICCONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_lblConnecting;
extern lv_obj_t * ui_spinnerBusy;
extern lv_obj_t * ui_imgLogo;
extern lv_obj_t * ui_lblTrafficController;
// SCREEN: ui_Panel1
void ui_Panel1_screen_init(void);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_school_logo_png);    // assets/school_logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
