// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef _ESP32_TRAFFICCONTROLLER_UI_H
#define _ESP32_TRAFFICCONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_PanelAllTraffic.h"
#include "screens/ui_Panel1.h"
#include "screens/ui_Panel2.h"
#include "screens/ui_Panel3.h"
#include "screens/ui_Panel4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_school_logo_png);    // assets/school_logo.png
LV_IMG_DECLARE(ui_img_338993590);    // assets/wifi-connected.png
LV_IMG_DECLARE(ui_img_traffic_light_png);    // assets/traffic_light.png
LV_IMG_DECLARE(ui_img_road_png);    // assets/road.png
LV_IMG_DECLARE(ui_img_1402433841);    // assets/wifi-disconnect.png
LV_IMG_DECLARE(ui_img_1688301267);    // assets/wifi-without-internet.png

// FONTS
LV_FONT_DECLARE(ui_font_DsDigital72);
LV_FONT_DECLARE(ui_font_SevenSegment48);
LV_FONT_DECLARE(ui_font_SevenSegment14);
LV_FONT_DECLARE(ui_font_SevenSegment18);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
