// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WeatherMonitor

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_lblProjectName = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblProjectName = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblProjectName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProjectName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProjectName, 0);
    lv_obj_set_y(ui_lblProjectName, 10);
    lv_obj_set_align(ui_lblProjectName, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblProjectName, "Weather Monitoring Station");
    lv_obj_set_style_text_color(ui_lblProjectName, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProjectName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProjectName, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_lblProjectName = NULL;

}
