// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WeatherMonitor

#ifndef UI_RESULTSBARSCREEN_H
#define UI_RESULTSBARSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ResultsBarScreen
extern void ui_ResultsBarScreen_screen_init(void);
extern void ui_ResultsBarScreen_screen_destroy(void);
extern lv_obj_t * ui_ResultsBarScreen;
extern lv_obj_t * ui_chartResults;
extern lv_obj_t * ui_lblElectionResults;
extern lv_obj_t * ui_panelBarChartLabel;
extern lv_obj_t * ui_lblBarParty1;
extern lv_obj_t * ui_lblBarParty2;
extern lv_obj_t * ui_lblBarParty3;
extern lv_obj_t * ui_lblBarParty4;
extern lv_obj_t * ui_lblBarParty5;
extern lv_obj_t * ui_lblBarParty6;
extern lv_obj_t * ui_lblBarParty7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

