// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WeatherMonitor

#include "../ui.h"

lv_obj_t * ui_SensorScreen = NULL;
lv_obj_t * ui_Header2 = NULL;
lv_obj_t * ui_lblProjectName2 = NULL;
lv_obj_t * ui_sensorPanel1 = NULL;
lv_obj_t * ui_sensorArc1 = NULL;
lv_obj_t * ui_sensorBg1 = NULL;
lv_obj_t * ui_SensorNumBg1 = NULL;
lv_obj_t * ui_lblSensor1 = NULL;
lv_obj_t * ui_lblTemperature = NULL;
lv_obj_t * ui_sensorPanel2 = NULL;
lv_obj_t * ui_sensorArc2 = NULL;
lv_obj_t * ui_sensorBg2 = NULL;
lv_obj_t * ui_SensorNumBg2 = NULL;
lv_obj_t * ui_lblSensor2 = NULL;
lv_obj_t * ui_lblHumidity = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_SensorScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_SensorScreen_screen_init(void)
{
    ui_SensorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SensorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SensorScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SensorScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header2 = lv_obj_create(ui_SensorScreen);
    lv_obj_set_height(ui_Header2, 50);
    lv_obj_set_width(ui_Header2, lv_pct(100));
    lv_obj_set_align(ui_Header2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Header2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header2, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProjectName2 = lv_label_create(ui_Header2);
    lv_obj_set_width(ui_lblProjectName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProjectName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblProjectName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProjectName2, "Weather Monitoring Station");
    lv_obj_set_style_text_color(ui_lblProjectName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProjectName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProjectName2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorPanel1 = lv_obj_create(ui_SensorScreen);
    lv_obj_set_width(ui_sensorPanel1, 400);
    lv_obj_set_height(ui_sensorPanel1, 400);
    lv_obj_set_x(ui_sensorPanel1, -200);
    lv_obj_set_y(ui_sensorPanel1, 10);
    lv_obj_set_align(ui_sensorPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sensorPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sensorPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sensorPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorArc1 = lv_arc_create(ui_sensorPanel1);
    lv_obj_set_width(ui_sensorArc1, 350);
    lv_obj_set_height(ui_sensorArc1, 350);
    lv_obj_set_align(ui_sensorArc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_sensorArc1, 5, 60);
    lv_arc_set_value(ui_sensorArc1, 35);
    lv_obj_set_style_radius(ui_sensorArc1, 350, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sensorArc1, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_sensorArc1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sensorArc1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sensorArc1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sensorArc1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_sensorArc1, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sensorArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_sensorArc1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_sensorArc1, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sensorArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_sensorArc1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sensorArc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_sensorBg1 = lv_obj_create(ui_sensorPanel1);
    lv_obj_set_width(ui_sensorBg1, 280);
    lv_obj_set_height(ui_sensorBg1, 280);
    lv_obj_set_align(ui_sensorBg1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sensorBg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sensorBg1, 280, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sensorBg1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorBg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_sensorBg1, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_sensorBg1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sensorBg1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sensorBg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sensorBg1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_sensorBg1, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_sensorBg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_sensorBg1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_sensorBg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_sensorBg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_sensorBg1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorNumBg1 = lv_obj_create(ui_sensorBg1);
    lv_obj_set_width(ui_SensorNumBg1, 200);
    lv_obj_set_height(ui_SensorNumBg1, 200);
    lv_obj_set_align(ui_SensorNumBg1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SensorNumBg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SensorNumBg1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SensorNumBg1, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorNumBg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SensorNumBg1, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SensorNumBg1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SensorNumBg1, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SensorNumBg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSensor1 = lv_label_create(ui_SensorNumBg1);
    lv_obj_set_width(ui_lblSensor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSensor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSensor1, 10);
    lv_obj_set_y(ui_lblSensor1, 0);
    lv_obj_set_align(ui_lblSensor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSensor1, "23°");
    lv_obj_set_style_text_color(ui_lblSensor1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSensor1, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTemperature = lv_label_create(ui_sensorPanel1);
    lv_obj_set_width(ui_lblTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemperature, 0);
    lv_obj_set_y(ui_lblTemperature, 20);
    lv_obj_set_align(ui_lblTemperature, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblTemperature, "Temperature");
    lv_obj_set_style_text_color(ui_lblTemperature, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTemperature, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorPanel2 = lv_obj_create(ui_SensorScreen);
    lv_obj_set_width(ui_sensorPanel2, 400);
    lv_obj_set_height(ui_sensorPanel2, 400);
    lv_obj_set_x(ui_sensorPanel2, 200);
    lv_obj_set_y(ui_sensorPanel2, 10);
    lv_obj_set_align(ui_sensorPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sensorPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sensorPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sensorPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorArc2 = lv_arc_create(ui_sensorPanel2);
    lv_obj_set_width(ui_sensorArc2, 350);
    lv_obj_set_height(ui_sensorArc2, 350);
    lv_obj_set_align(ui_sensorArc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_sensorArc2, 5, 100);
    lv_arc_set_value(ui_sensorArc2, 80);
    lv_obj_set_style_radius(ui_sensorArc2, 350, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sensorArc2, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorArc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_sensorArc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sensorArc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sensorArc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sensorArc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_sensorArc2, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sensorArc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_sensorArc2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_sensorArc2, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_sensorArc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_sensorArc2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sensorArc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorArc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_sensorBg2 = lv_obj_create(ui_sensorPanel2);
    lv_obj_set_width(ui_sensorBg2, 280);
    lv_obj_set_height(ui_sensorBg2, 280);
    lv_obj_set_align(ui_sensorBg2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sensorBg2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sensorBg2, 280, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sensorBg2, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorBg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_sensorBg2, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_sensorBg2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sensorBg2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sensorBg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sensorBg2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_sensorBg2, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_sensorBg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_sensorBg2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_sensorBg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_sensorBg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_sensorBg2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorNumBg2 = lv_obj_create(ui_sensorBg2);
    lv_obj_set_width(ui_SensorNumBg2, 200);
    lv_obj_set_height(ui_SensorNumBg2, 200);
    lv_obj_set_align(ui_SensorNumBg2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SensorNumBg2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SensorNumBg2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SensorNumBg2, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorNumBg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SensorNumBg2, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SensorNumBg2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SensorNumBg2, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SensorNumBg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSensor2 = lv_label_create(ui_SensorNumBg2);
    lv_obj_set_width(ui_lblSensor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSensor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSensor2, 10);
    lv_obj_set_y(ui_lblSensor2, 0);
    lv_obj_set_align(ui_lblSensor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSensor2, "80%");
    lv_obj_set_style_text_color(ui_lblSensor2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSensor2, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHumidity = lv_label_create(ui_sensorPanel2);
    lv_obj_set_width(ui_lblHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHumidity, 0);
    lv_obj_set_y(ui_lblHumidity, 20);
    lv_obj_set_align(ui_lblHumidity, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblHumidity, "Humidity");
    lv_obj_set_style_text_color(ui_lblHumidity, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHumidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_SensorScreen);
    lv_img_set_src(ui_Image1, &ui_img_wifi_connected_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -10);
    lv_obj_set_y(ui_Image1, -10);
    lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SensorScreen, ui_event_SensorScreen, LV_EVENT_ALL, NULL);

}

void ui_SensorScreen_screen_destroy(void)
{
    if(ui_SensorScreen) lv_obj_del(ui_SensorScreen);

    // NULL screen variables
    ui_SensorScreen = NULL;
    ui_Header2 = NULL;
    ui_lblProjectName2 = NULL;
    ui_sensorPanel1 = NULL;
    ui_sensorArc1 = NULL;
    ui_sensorBg1 = NULL;
    ui_SensorNumBg1 = NULL;
    ui_lblSensor1 = NULL;
    ui_lblTemperature = NULL;
    ui_sensorPanel2 = NULL;
    ui_sensorArc2 = NULL;
    ui_sensorBg2 = NULL;
    ui_SensorNumBg2 = NULL;
    ui_lblSensor2 = NULL;
    ui_lblHumidity = NULL;
    ui_Image1 = NULL;

}
