// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WeatherMonitor

#ifndef UI_SENSORSCREEN_H
#define UI_SENSORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorScreen
extern void ui_SensorScreen_screen_init(void);
extern void ui_SensorScreen_screen_destroy(void);
extern void ui_event_SensorScreen(lv_event_t * e);
extern lv_obj_t * ui_SensorScreen;
extern lv_obj_t * ui_Header2;
extern lv_obj_t * ui_lblProjectName2;
extern lv_obj_t * ui_sensorPanel1;
extern lv_obj_t * ui_sensorArc1;
extern lv_obj_t * ui_sensorBg1;
extern lv_obj_t * ui_SensorNumBg1;
extern lv_obj_t * ui_lblSensor1;
extern lv_obj_t * ui_lblTemperature;
extern lv_obj_t * ui_sensorPanel2;
extern lv_obj_t * ui_sensorArc2;
extern lv_obj_t * ui_sensorBg2;
extern lv_obj_t * ui_SensorNumBg2;
extern lv_obj_t * ui_lblSensor2;
extern lv_obj_t * ui_lblHumidity;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

