// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WeatherMonitor

#ifndef UI_SENSORSCREEN_H
#define UI_SENSORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorScreen
extern void ui_SensorScreen_screen_init(void);
extern void ui_SensorScreen_screen_destroy(void);
extern void ui_event_SensorScreen(lv_event_t * e);
extern lv_obj_t * ui_SensorScreen;
extern lv_obj_t * ui_panelHeaderSensorScreen;
extern lv_obj_t * ui_lblProjectNameSensorScreen;
extern lv_obj_t * ui_imgWiFiStatus2;
extern lv_obj_t * ui_panelSensor1;
extern lv_obj_t * ui_arcSensor1;
extern lv_obj_t * ui_panelBgSensor1;
extern lv_obj_t * ui_panelNumBgSensor1;
extern lv_obj_t * ui_lblSensor1;
extern lv_obj_t * ui_lblTemperature;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

