// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Delhi
void ui_Delhi_screen_init(void);
lv_obj_t * ui_Delhi;
lv_obj_t * ui_delhiImage;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Pressure;
lv_obj_t * ui_tempValue;
lv_obj_t * ui_pressureValue;

// SCREEN: ui_Shimla
void ui_Shimla_screen_init(void);
lv_obj_t * ui_Shimla;
lv_obj_t * ui_shimlaImage;

// SCREEN: ui_Jaipur
void ui_Jaipur_screen_init(void);
lv_obj_t * ui_Jaipur;
lv_obj_t * ui_jaipurImage;

// SCREEN: ui_Leh
void ui_Leh_screen_init(void);
lv_obj_t * ui_Leh;
lv_obj_t * ui_lehImage;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Delhi_screen_init();
    ui_Shimla_screen_init();
    ui_Jaipur_screen_init();
    ui_Leh_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Delhi);
}
