// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_delhiImage;
lv_obj_t * ui_Temperature0;
lv_obj_t * ui_Pressure0;
lv_obj_t * ui_tempValue0;
lv_obj_t * ui_pressureValue0;
lv_obj_t * ui_Humidity0;
lv_obj_t * ui_humidityValue0;
lv_obj_t * ui_CityName0;
lv_obj_t * ui_cityNameValue0;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_shimlaImage;
lv_obj_t * ui_Temperature1;
lv_obj_t * ui_Pressure1;
lv_obj_t * ui_tempValue1;
lv_obj_t * ui_pressureValue1;
lv_obj_t * ui_Humidity1;
lv_obj_t * ui_humidityValue1;
lv_obj_t * ui_CityName1;
lv_obj_t * ui_cityNameValue1;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_jaipurImage;
lv_obj_t * ui_Temperature2;
lv_obj_t * ui_Pressure2;
lv_obj_t * ui_tempValue2;
lv_obj_t * ui_pressureValue2;
lv_obj_t * ui_Humidity2;
lv_obj_t * ui_humidityValue2;
lv_obj_t * ui_CityName2;
lv_obj_t * ui_cityNameValue2;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_lehImage;
lv_obj_t * ui_Temperature3;
lv_obj_t * ui_Pressure3;
lv_obj_t * ui_tempValue3;
lv_obj_t * ui_pressureValue3;
lv_obj_t * ui_Humidity3;
lv_obj_t * ui_humidityValue3;
lv_obj_t * ui_CityName3;
lv_obj_t * ui_cityNameValue3;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
