// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenWeatherMap

#ifndef _OPENWEATHERMAP_UI_H
#define _OPENWEATHERMAP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_delhiImage;
extern lv_obj_t * ui_Temperature0;
extern lv_obj_t * ui_Pressure0;
extern lv_obj_t * ui_tempValue0;
extern lv_obj_t * ui_pressureValue0;
extern lv_obj_t * ui_Humidity0;
extern lv_obj_t * ui_humidityValue0;
extern lv_obj_t * ui_CityName0;
extern lv_obj_t * ui_cityNameValue0;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_shimlaImage;
extern lv_obj_t * ui_Temperature1;
extern lv_obj_t * ui_Pressure1;
extern lv_obj_t * ui_tempValue1;
extern lv_obj_t * ui_pressureValue1;
extern lv_obj_t * ui_Humidity1;
extern lv_obj_t * ui_humidityValue1;
extern lv_obj_t * ui_CityName1;
extern lv_obj_t * ui_cityNameValue1;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_jaipurImage;
extern lv_obj_t * ui_Temperature2;
extern lv_obj_t * ui_Pressure2;
extern lv_obj_t * ui_tempValue2;
extern lv_obj_t * ui_pressureValue2;
extern lv_obj_t * ui_Humidity2;
extern lv_obj_t * ui_humidityValue2;
extern lv_obj_t * ui_CityName2;
extern lv_obj_t * ui_cityNameValue2;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_lehImage;
extern lv_obj_t * ui_Temperature3;
extern lv_obj_t * ui_Pressure3;
extern lv_obj_t * ui_tempValue3;
extern lv_obj_t * ui_pressureValue3;
extern lv_obj_t * ui_Humidity3;
extern lv_obj_t * ui_humidityValue3;
extern lv_obj_t * ui_CityName3;
extern lv_obj_t * ui_cityNameValue3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_delhi_png);    // assets\Delhi.png
LV_IMG_DECLARE(ui_img_shimla_png);    // assets\Shimla.png
LV_IMG_DECLARE(ui_img_jaipur_png);    // assets\Jaipur.png
LV_IMG_DECLARE(ui_img_leh_png);    // assets\Leh.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
