// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoffeeAnimation

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x292431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgCoffeeCup = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_imgCoffeeCup, &ui_img_coffee_f01_png);
    lv_obj_set_width(ui_imgCoffeeCup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgCoffeeCup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgCoffeeCup, 0);
    lv_obj_set_y(ui_imgCoffeeCup, 15);
    lv_obj_set_align(ui_imgCoffeeCup, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_imgCoffeeCup, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgCoffeeCup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnFillCup = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_btnFillCup, 100);
    lv_obj_set_height(ui_btnFillCup, 30);
    lv_obj_set_x(ui_btnFillCup, 0);
    lv_obj_set_y(ui_btnFillCup, -5);
    lv_obj_set_align(ui_btnFillCup, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnFillCup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFillCup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnFillCup, lv_color_hex(0x413C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnFillCup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFillCup = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblFillCup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFillCup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFillCup, 0);
    lv_obj_set_y(ui_lblFillCup, -12);
    lv_obj_set_align(ui_lblFillCup, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblFillCup, "Fill Cup");
    lv_obj_set_style_text_align(ui_lblFillCup, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnFillCup, ui_event_btnFillCup, LV_EVENT_ALL, NULL);

}
