// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: VotingMachine

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_panelMain;
lv_obj_t * ui_panelParty1;
lv_obj_t * ui_lblPartyName;
lv_obj_t * ui_imgPartyLogo1;
lv_obj_t * ui_btnVoteParty1;
lv_obj_t * ui_lblPartyTotalVotes1;
lv_obj_t * ui_lblPartyTotalVotesPercentage1;
lv_obj_t * ui_panelParty2;
lv_obj_t * ui_lblPartyName1;
lv_obj_t * ui_imgPartyLogo2;
lv_obj_t * ui_btnVoteParty2;
lv_obj_t * ui_lblPartyTotalVotes2;
lv_obj_t * ui_lblPartyTotalVotesPercentage2;
lv_obj_t * ui_panelParty3;
lv_obj_t * ui_lblPartyName2;
lv_obj_t * ui_imgPartyLogo3;
lv_obj_t * ui_btnVoteParty3;
lv_obj_t * ui_lblPartyTotalVotes3;
lv_obj_t * ui_lblPartyTotalVotesPercentage3;
lv_obj_t * ui_lblTitle;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
