// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: VotingMachine

#ifndef _VOTINGMACHINE_UI_H
#define _VOTINGMACHINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_panelMain;
extern lv_obj_t * ui_panelParty1;
extern lv_obj_t * ui_lblPartyName;
extern lv_obj_t * ui_imgPartyLogo1;
extern lv_obj_t * ui_btnVoteParty1;
extern lv_obj_t * ui_lblPartyTotalVotes1;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage1;
extern lv_obj_t * ui_panelParty2;
extern lv_obj_t * ui_lblPartyName1;
extern lv_obj_t * ui_imgPartyLogo2;
extern lv_obj_t * ui_btnVoteParty2;
extern lv_obj_t * ui_lblPartyTotalVotes2;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage2;
extern lv_obj_t * ui_panelParty3;
extern lv_obj_t * ui_lblPartyName2;
extern lv_obj_t * ui_imgPartyLogo3;
extern lv_obj_t * ui_btnVoteParty3;
extern lv_obj_t * ui_lblPartyTotalVotes3;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage3;
extern lv_obj_t * ui_lblTitle;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bjp_png);    // assets/BJP.png
LV_IMG_DECLARE(ui_img_bsp_png);    // assets/BSP.png
LV_IMG_DECLARE(ui_img_cpi_png);    // assets/CPI.png
LV_IMG_DECLARE(ui_img_aap_png);    // assets/AAP.png
LV_IMG_DECLARE(ui_img_congress_png);    // assets/Congress.png
LV_IMG_DECLARE(ui_img_ncp_png);    // assets/NCP.png
LV_IMG_DECLARE(ui_img_sp_png);    // assets/SP.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
