// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: VotingMachine

#ifndef _VOTINGMACHINE_UI_H
#define _VOTINGMACHINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_panelMain;
extern lv_obj_t * ui_panelParty1;
extern lv_obj_t * ui_lblPartyName1;
extern lv_obj_t * ui_imgPartyLogo1;
extern lv_obj_t * ui_btnVoteParty1;
extern lv_obj_t * ui_lblVoteParty1;
extern lv_obj_t * ui_lblPartyTotalVotes1;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage1;
extern lv_obj_t * ui_panelParty2;
extern lv_obj_t * ui_lblPartyName2;
extern lv_obj_t * ui_imgPartyLogo2;
extern lv_obj_t * ui_btnVoteParty2;
extern lv_obj_t * ui_lblVoteParty2;
extern lv_obj_t * ui_lblPartyTotalVotes2;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage2;
extern lv_obj_t * ui_panelParty3;
extern lv_obj_t * ui_lblPartyName3;
extern lv_obj_t * ui_imgPartyLogo3;
extern lv_obj_t * ui_btnVoteParty3;
extern lv_obj_t * ui_lblVoteParty3;
extern lv_obj_t * ui_lblPartyTotalVotes3;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage3;
extern lv_obj_t * ui_panelParty4;
extern lv_obj_t * ui_lblPartyName4;
extern lv_obj_t * ui_imgPartyLogo4;
extern lv_obj_t * ui_btnVoteParty4;
extern lv_obj_t * ui_lblVoteParty4;
extern lv_obj_t * ui_lblPartyTotalVotes4;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage4;
extern lv_obj_t * ui_panelParty5;
extern lv_obj_t * ui_lblPartyName5;
extern lv_obj_t * ui_imgPartyLogo5;
extern lv_obj_t * ui_btnVoteParty5;
extern lv_obj_t * ui_lblVoteParty5;
extern lv_obj_t * ui_lblPartyTotalVotes5;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage5;
extern lv_obj_t * ui_panelParty6;
extern lv_obj_t * ui_lblPartyName6;
extern lv_obj_t * ui_imgPartyLogo6;
extern lv_obj_t * ui_btnVoteParty6;
extern lv_obj_t * ui_lblVoteParty6;
extern lv_obj_t * ui_lblPartyTotalVotes6;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage6;
extern lv_obj_t * ui_panelParty7;
extern lv_obj_t * ui_lblPartyName7;
extern lv_obj_t * ui_imgPartyLogo7;
extern lv_obj_t * ui_btnVoteParty7;
extern lv_obj_t * ui_lblVoteParty7;
extern lv_obj_t * ui_lblPartyTotalVotes7;
extern lv_obj_t * ui_lblPartyTotalVotesPercentage7;
extern lv_obj_t * ui_lblTitle;
extern lv_obj_t * ui_btnResults;
extern lv_obj_t * ui_lblResults;
extern lv_obj_t * ui_btnReset;
extern lv_obj_t * ui_lblReset;
// SCREEN: ui_ResultsBarScreen
void ui_ResultsBarScreen_screen_init(void);
extern lv_obj_t * ui_ResultsBarScreen;
extern lv_obj_t * ui_chartResults;
extern lv_obj_t * ui_lblElectionResults;
extern lv_obj_t * ui_panelBarChartLabel;
extern lv_obj_t * ui_lblBarParty1;
extern lv_obj_t * ui_lblBarParty2;
extern lv_obj_t * ui_lblBarParty3;
extern lv_obj_t * ui_lblBarParty4;
extern lv_obj_t * ui_lblBarParty5;
extern lv_obj_t * ui_lblBarParty6;
extern lv_obj_t * ui_lblBarParty7;
extern lv_obj_t * ui_lblBarParty8;
extern lv_obj_t * ui_lblBarParty9;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_na_png);    // assets/NA.png
LV_IMG_DECLARE(ui_img_images_original_jdu_png);    // assets/images_original/JDU.png
LV_IMG_DECLARE(ui_img_images_original_tmc_png);    // assets/images_original/TMC.png
LV_IMG_DECLARE(ui_img_aap_png);    // assets/AAP.png
LV_IMG_DECLARE(ui_img_bjp_png);    // assets/BJP.png
LV_IMG_DECLARE(ui_img_bsp_png);    // assets/BSP.png
LV_IMG_DECLARE(ui_img_congress_png);    // assets/Congress.png
LV_IMG_DECLARE(ui_img_cpi_png);    // assets/CPI.png
LV_IMG_DECLARE(ui_img_jdu_png);    // assets/JDU.png
LV_IMG_DECLARE(ui_img_ncp_png);    // assets/NCP.png
LV_IMG_DECLARE(ui_img_sp_png);    // assets/SP.png
LV_IMG_DECLARE(ui_img_tmc_png);    // assets/TMC.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
