// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: VotingMachine

#include "../ui.h"

void ui_ResultsBarScreen_screen_init(void)
{
    ui_ResultsBarScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ResultsBarScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chartResults = lv_chart_create(ui_ResultsBarScreen);
    lv_obj_set_width(ui_chartResults, 700);
    lv_obj_set_height(ui_chartResults, 380);
    lv_obj_set_align(ui_chartResults, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_chartResults, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_chartResults, 9);
    lv_chart_set_range(ui_chartResults, LV_CHART_AXIS_PRIMARY_Y, 0, 10);
    lv_chart_set_range(ui_chartResults, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_axis_tick(ui_chartResults, LV_CHART_AXIS_PRIMARY_X, 10, 5, 7, 2, false, 50);
    lv_chart_set_axis_tick(ui_chartResults, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_chartResults, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_chartResults_series_1 = lv_chart_add_series(ui_chartResults, lv_color_hex(0x5B7C72),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chartResults_series_1_array[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    lv_chart_set_ext_y_array(ui_chartResults, ui_chartResults_series_1, ui_chartResults_series_1_array);



    ui_lblElectionResults = lv_label_create(ui_ResultsBarScreen);
    lv_obj_set_width(ui_lblElectionResults, 400);
    lv_obj_set_height(ui_lblElectionResults, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_lblElectionResults, 0);
    lv_obj_set_y(ui_lblElectionResults, 5);
    lv_obj_set_align(ui_lblElectionResults, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblElectionResults, "Election Results");
    lv_obj_set_style_text_align(ui_lblElectionResults, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblElectionResults, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelBarChartLabel = lv_obj_create(ui_ResultsBarScreen);
    lv_obj_set_width(ui_panelBarChartLabel, 700);
    lv_obj_set_height(ui_panelBarChartLabel, 30);
    lv_obj_set_x(ui_panelBarChartLabel, 0);
    lv_obj_set_y(ui_panelBarChartLabel, -10);
    lv_obj_set_align(ui_panelBarChartLabel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_panelBarChartLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelBarChartLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelBarChartLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblBarParty1 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty1, 20);
    lv_obj_set_flex_grow(ui_lblBarParty1, 1);
    lv_obj_set_align(ui_lblBarParty1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty1, "-");
    lv_obj_set_style_text_align(ui_lblBarParty1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty2 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty2, 20);
    lv_obj_set_flex_grow(ui_lblBarParty2, 1);
    lv_obj_set_align(ui_lblBarParty2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty2, "-");
    lv_obj_set_style_text_align(ui_lblBarParty2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty3 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty3, 20);
    lv_obj_set_flex_grow(ui_lblBarParty3, 1);
    lv_obj_set_align(ui_lblBarParty3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty3, "-");
    lv_obj_set_style_text_align(ui_lblBarParty3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty4 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty4, 20);
    lv_obj_set_flex_grow(ui_lblBarParty4, 1);
    lv_obj_set_align(ui_lblBarParty4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty4, "-");
    lv_obj_set_style_text_align(ui_lblBarParty4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty5 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty5, 20);
    lv_obj_set_flex_grow(ui_lblBarParty5, 1);
    lv_obj_set_align(ui_lblBarParty5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty5, "-");
    lv_obj_set_style_text_align(ui_lblBarParty5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty6 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty6, 20);
    lv_obj_set_flex_grow(ui_lblBarParty6, 1);
    lv_obj_set_align(ui_lblBarParty6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty6, "-");
    lv_obj_set_style_text_align(ui_lblBarParty6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty7 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty7, 20);
    lv_obj_set_flex_grow(ui_lblBarParty7, 1);
    lv_obj_set_align(ui_lblBarParty7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty7, "-");
    lv_obj_set_style_text_align(ui_lblBarParty7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty8 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty8, 20);
    lv_obj_set_flex_grow(ui_lblBarParty8, 1);
    lv_obj_set_align(ui_lblBarParty8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty8, "-");
    lv_obj_set_style_text_align(ui_lblBarParty8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBarParty9 = lv_label_create(ui_panelBarChartLabel);
    lv_obj_set_height(ui_lblBarParty9, 20);
    lv_obj_set_flex_grow(ui_lblBarParty9, 1);
    lv_obj_set_align(ui_lblBarParty9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBarParty9, "-");
    lv_obj_set_style_text_align(ui_lblBarParty9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBarParty9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
