// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WeatherMonitor

#ifndef _WEATHERMONITOR_UI_H
#define _WEATHERMONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SensorScreen.h"
#include "screens/ui_MainScreen.h"
#include "screens/ui_SensorScreenBackup.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_disconnected_png);    // assets/wifi_disconnected.png
LV_IMG_DECLARE(ui_img_school_logo_png);    // assets/school_logo.png
LV_IMG_DECLARE(ui_img_wifi_connected_png);    // assets/wifi_connected.png
LV_IMG_DECLARE(ui_img_2479933);    // assets/school_logo-original.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
