// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TemperateHumidity

#ifndef _TEMPERATEHUMIDITY_UI_H
#define _TEMPERATEHUMIDITY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_lblHeadLine;
extern lv_obj_t * ui_lblTemperature;
extern lv_obj_t * ui_lblHumidity;
extern lv_obj_t * ui_lblTemperatureValue;
extern lv_obj_t * ui_lblHumidityValue;
void ui_event_cbLanguageSelection(lv_event_t * e);
extern lv_obj_t * ui_cbLanguageSelection;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_mangal);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
