// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoffeeAnimation

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void FillCupAnimation_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_imgCoffeeCup;
void ui_event_btnFillCup(lv_event_t * e);
lv_obj_t * ui_btnFillCup;
lv_obj_t * ui_lblFillCup;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_coffee_f[31] = {&ui_img_coffee_f01_png, &ui_img_coffee_f02_png, &ui_img_coffee_f03_png, &ui_img_coffee_f04_png, &ui_img_coffee_f05_png, &ui_img_coffee_f06_png, &ui_img_coffee_f07_png, &ui_img_coffee_f08_png, &ui_img_coffee_f09_png, &ui_img_coffee_f10_png, &ui_img_coffee_f11_png, &ui_img_coffee_f12_png, &ui_img_coffee_f13_png, &ui_img_coffee_f14_png, &ui_img_coffee_f15_png, &ui_img_coffee_f16_png, &ui_img_coffee_f17_png, &ui_img_coffee_f18_png, &ui_img_coffee_f19_png, &ui_img_coffee_f20_png, &ui_img_coffee_f21_png, &ui_img_coffee_f22_png, &ui_img_coffee_f23_png, &ui_img_coffee_f24_png, &ui_img_coffee_f25_png, &ui_img_coffee_f26_png, &ui_img_coffee_f27_png, &ui_img_coffee_f28_png, &ui_img_coffee_f29_png, &ui_img_coffee_f30_png, &ui_img_coffee_f31_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void FillCupAnimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = ui_imgset_coffee_f;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_coffee_f) / (sizeof(lv_img_dsc_t *));
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 3000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 31);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnFillCup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        FillCupAnimation_Animation(ui_imgCoffeeCup, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
