// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CoffeeAnimation

#ifndef _COFFEEANIMATION_UI_H
#define _COFFEEANIMATION_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void FillCupAnimation_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_imgCoffeeCup;
void ui_event_btnFillCup(lv_event_t * e);
extern lv_obj_t * ui_btnFillCup;
extern lv_obj_t * ui_lblFillCup;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_coffee_f01_png);    // assets\coffee_f01.png
LV_IMG_DECLARE(ui_img_coffee_f02_png);    // assets\coffee_f02.png
LV_IMG_DECLARE(ui_img_coffee_f03_png);    // assets\coffee_f03.png
LV_IMG_DECLARE(ui_img_coffee_f04_png);    // assets\coffee_f04.png
LV_IMG_DECLARE(ui_img_coffee_f05_png);    // assets\coffee_f05.png
LV_IMG_DECLARE(ui_img_coffee_f06_png);    // assets\coffee_f06.png
LV_IMG_DECLARE(ui_img_coffee_f07_png);    // assets\coffee_f07.png
LV_IMG_DECLARE(ui_img_coffee_f08_png);    // assets\coffee_f08.png
LV_IMG_DECLARE(ui_img_coffee_f09_png);    // assets\coffee_f09.png
LV_IMG_DECLARE(ui_img_coffee_f10_png);    // assets\coffee_f10.png
LV_IMG_DECLARE(ui_img_coffee_f11_png);    // assets\coffee_f11.png
LV_IMG_DECLARE(ui_img_coffee_f12_png);    // assets\coffee_f12.png
LV_IMG_DECLARE(ui_img_coffee_f13_png);    // assets\coffee_f13.png
LV_IMG_DECLARE(ui_img_coffee_f14_png);    // assets\coffee_f14.png
LV_IMG_DECLARE(ui_img_coffee_f15_png);    // assets\coffee_f15.png
LV_IMG_DECLARE(ui_img_coffee_f16_png);    // assets\coffee_f16.png
LV_IMG_DECLARE(ui_img_coffee_f17_png);    // assets\coffee_f17.png
LV_IMG_DECLARE(ui_img_coffee_f18_png);    // assets\coffee_f18.png
LV_IMG_DECLARE(ui_img_coffee_f19_png);    // assets\coffee_f19.png
LV_IMG_DECLARE(ui_img_coffee_f20_png);    // assets\coffee_f20.png
LV_IMG_DECLARE(ui_img_coffee_f21_png);    // assets\coffee_f21.png
LV_IMG_DECLARE(ui_img_coffee_f22_png);    // assets\coffee_f22.png
LV_IMG_DECLARE(ui_img_coffee_f23_png);    // assets\coffee_f23.png
LV_IMG_DECLARE(ui_img_coffee_f24_png);    // assets\coffee_f24.png
LV_IMG_DECLARE(ui_img_coffee_f25_png);    // assets\coffee_f25.png
LV_IMG_DECLARE(ui_img_coffee_f26_png);    // assets\coffee_f26.png
LV_IMG_DECLARE(ui_img_coffee_f27_png);    // assets\coffee_f27.png
LV_IMG_DECLARE(ui_img_coffee_f28_png);    // assets\coffee_f28.png
LV_IMG_DECLARE(ui_img_coffee_f29_png);    // assets\coffee_f29.png
LV_IMG_DECLARE(ui_img_coffee_f30_png);    // assets\coffee_f30.png
LV_IMG_DECLARE(ui_img_coffee_f31_png);    // assets\coffee_f31.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
