// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ESP32_Clock

#include "../ui.h"

void ui_ClockScreen_screen_init(void)
{
    ui_ClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ClockScreen, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBackground = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_imgBackground, &ui_img_bg_png);
    lv_obj_set_width(ui_imgBackground, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBackground, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgSecDot = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_imgSecDot, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_imgSecDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgSecDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgSecDot, 0);
    lv_obj_set_y(ui_imgSecDot, -115);
    lv_obj_set_align(ui_imgSecDot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgSecDot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgSecDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_imgSecDot, 4, 118);

    ui_imgHour = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_imgHour, &ui_img_clock_hour_png);
    lv_obj_set_width(ui_imgHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgHour, 0);
    lv_obj_set_y(ui_imgHour, -34);
    lv_obj_set_align(ui_imgHour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgHour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_imgHour, 9, 77);

    ui_imgMinute = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_imgMinute, &ui_img_clock_min_png);
    lv_obj_set_width(ui_imgMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgMinute, 0);
    lv_obj_set_y(ui_imgMinute, -48);
    lv_obj_set_align(ui_imgMinute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMinute, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMinute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_imgMinute, 9, 105);

    ui_imgSecond = lv_img_create(ui_ClockScreen);
    lv_img_set_src(ui_imgSecond, &ui_img_clock_sec_png);
    lv_obj_set_width(ui_imgSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgSecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgSecond, 0);
    lv_obj_set_y(ui_imgSecond, -26);
    lv_obj_set_align(ui_imgSecond, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgSecond, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgSecond, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_imgSecond, 5, 95);
    lv_img_set_angle(ui_imgSecond, 9);

}
