// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_imgLogo = NULL;
lv_obj_t * ui_lblTrafficController = NULL;
lv_obj_t * ui_imgConnectStatus = NULL;
lv_obj_t * ui_lblDebug = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgLogo = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_imgLogo, &ui_img_school_logo_png);
    lv_obj_set_width(ui_imgLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgLogo, 0);
    lv_obj_set_y(ui_imgLogo, 25);
    lv_obj_set_align(ui_imgLogo, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_imgLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgLogo, 200);

    ui_lblTrafficController = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblTrafficController, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTrafficController, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTrafficController, 0);
    lv_obj_set_y(ui_lblTrafficController, 5);
    lv_obj_set_align(ui_lblTrafficController, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTrafficController, "MLBTLS: Machine Learning\nBased Traffic Light System");
    lv_obj_set_style_text_color(ui_lblTrafficController, lv_color_hex(0x527131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTrafficController, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTrafficController, &ui_font_MontserratExtraBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgConnectStatus = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_imgConnectStatus, &ui_img_338993590);
    lv_obj_set_width(ui_imgConnectStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgConnectStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgConnectStatus, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_imgConnectStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgConnectStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblDebug = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblDebug, 320);
    lv_obj_set_height(ui_lblDebug, 180);
    lv_obj_set_align(ui_lblDebug, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblDebug, "Hello World");
    lv_obj_add_flag(ui_lblDebug, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_lblDebug, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDebug, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDebug, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_imgLogo = NULL;
    ui_lblTrafficController = NULL;
    ui_imgConnectStatus = NULL;
    ui_lblDebug = NULL;

}
