// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef UI_PANEL3_H
#define UI_PANEL3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Panel3
extern void ui_Panel3_screen_init(void);
extern void ui_Panel3_screen_destroy(void);
extern void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_lblSide3;
extern lv_obj_t * ui_imgConnectStatus3;
extern lv_obj_t * ui_imgHousing4;
extern lv_obj_t * ui_lblYellowTime3;
extern lv_obj_t * ui_lblGreenTime3;
extern lv_obj_t * ui_lblRedTime3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

