// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#include "../ui.h"

lv_obj_t * ui_PanelAllTraffic = NULL;
// event funtions

// build funtions

void ui_PanelAllTraffic_screen_init(void)
{
    ui_PanelAllTraffic = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PanelAllTraffic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_PanelAllTraffic_screen_destroy(void)
{
    if(ui_PanelAllTraffic) lv_obj_del(ui_PanelAllTraffic);

    // NULL screen variables
    ui_PanelAllTraffic = NULL;

}
