// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#include "../ui.h"

void ui_Panel2_screen_init(void)
{
    ui_Panel2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSide2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblSide2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSide2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSide2, 0);
    lv_obj_set_y(ui_lblSide2, 5);
    lv_obj_set_align(ui_lblSide2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSide2, "SIDE-2");
    lv_obj_set_style_text_color(ui_lblSide2, lv_color_hex(0x5A7131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSide2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSide2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgConnectStatus2 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_imgConnectStatus2, &ui_img_1688301267);
    lv_obj_set_width(ui_imgConnectStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgConnectStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgConnectStatus2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_imgConnectStatus2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgConnectStatus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblYellowTime2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblYellowTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblYellowTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblYellowTime2, 60);
    lv_obj_set_y(ui_lblYellowTime2, 20);
    lv_obj_set_align(ui_lblYellowTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYellowTime2, "00");
    lv_obj_set_style_text_color(ui_lblYellowTime2, lv_color_hex(0xC8C800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblYellowTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblYellowTime2, &ui_font_SevenSegment48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGreenTime2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblGreenTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGreenTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGreenTime2, 60);
    lv_obj_set_y(ui_lblGreenTime2, -39);
    lv_obj_set_align(ui_lblGreenTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGreenTime2, "00");
    lv_obj_set_style_text_color(ui_lblGreenTime2, lv_color_hex(0x008000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGreenTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGreenTime2, &ui_font_SevenSegment48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRedTime2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblRedTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRedTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRedTime2, 60);
    lv_obj_set_y(ui_lblRedTime2, 80);
    lv_obj_set_align(ui_lblRedTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRedTime2, "00");
    lv_obj_set_style_text_color(ui_lblRedTime2, lv_color_hex(0x800000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRedTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRedTime2, &ui_font_SevenSegment48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);

}
