// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef UI_PANEL4_H
#define UI_PANEL4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Panel4
extern void ui_Panel4_screen_init(void);
extern void ui_Panel4_screen_destroy(void);
extern void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_lblSide4;
extern lv_obj_t * ui_imgConnectStatus4;
extern lv_obj_t * ui_lblYellowTime4;
extern lv_obj_t * ui_lblGreenTime4;
extern lv_obj_t * ui_lblRedTime4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

