// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#include "../ui.h"

void ui_Panel1_screen_init(void)
{
    ui_Panel1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
