// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#include "../ui.h"

lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_lblSide4 = NULL;
lv_obj_t * ui_imgConnectStatus4 = NULL;
lv_obj_t * ui_imgHousing5 = NULL;
lv_obj_t * ui_lblYellowTime4 = NULL;
lv_obj_t * ui_lblGreenTime4 = NULL;
lv_obj_t * ui_lblRedTime4 = NULL;
// event funtions
void ui_event_Panel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Panel3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Panel3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PanelAllTraffic, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PanelAllTraffic_screen_init);
    }
}

// build funtions

void ui_Panel4_screen_init(void)
{
    ui_Panel4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Panel4, &ui_img_road_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSide4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblSide4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSide4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSide4, 0);
    lv_obj_set_y(ui_lblSide4, 5);
    lv_obj_set_align(ui_lblSide4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSide4, "SIDE-4");
    lv_obj_set_style_text_font(ui_lblSide4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgConnectStatus4 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_imgConnectStatus4, &ui_img_1688301267);
    lv_obj_set_width(ui_imgConnectStatus4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgConnectStatus4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgConnectStatus4, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_imgConnectStatus4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgConnectStatus4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHousing5 = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_imgHousing5, &ui_img_traffic_light_housing_png);
    lv_obj_set_width(ui_imgHousing5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgHousing5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgHousing5, -60);
    lv_obj_set_y(ui_imgHousing5, 20);
    lv_obj_set_align(ui_imgHousing5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgHousing5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgHousing5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblYellowTime4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblYellowTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblYellowTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblYellowTime4, 60);
    lv_obj_set_y(ui_lblYellowTime4, 20);
    lv_obj_set_align(ui_lblYellowTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYellowTime4, "00");
    lv_obj_set_style_text_font(ui_lblYellowTime4, &ui_font_SevenSegment48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGreenTime4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblGreenTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGreenTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGreenTime4, 60);
    lv_obj_set_y(ui_lblGreenTime4, -40);
    lv_obj_set_align(ui_lblGreenTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGreenTime4, "00");
    lv_obj_set_style_text_font(ui_lblGreenTime4, &ui_font_SevenSegment48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRedTime4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblRedTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRedTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRedTime4, 60);
    lv_obj_set_y(ui_lblRedTime4, 80);
    lv_obj_set_align(ui_lblRedTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRedTime4, "00");
    lv_obj_set_style_text_font(ui_lblRedTime4, &ui_font_SevenSegment48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);

}

void ui_Panel4_screen_destroy(void)
{
    if(ui_Panel4) lv_obj_del(ui_Panel4);

    // NULL screen variables
    ui_Panel4 = NULL;
    ui_lblSide4 = NULL;
    ui_imgConnectStatus4 = NULL;
    ui_imgHousing5 = NULL;
    ui_lblYellowTime4 = NULL;
    ui_lblGreenTime4 = NULL;
    ui_lblRedTime4 = NULL;

}
