// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef UI_PANELALLTRAFFIC_H
#define UI_PANELALLTRAFFIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PanelAllTraffic
extern void ui_PanelAllTraffic_screen_init(void);
extern void ui_PanelAllTraffic_screen_destroy(void);
extern lv_obj_t * ui_PanelAllTraffic;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

