// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef UI_PANEL1_H
#define UI_PANEL1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Panel1
extern void ui_Panel1_screen_init(void);
extern void ui_Panel1_screen_destroy(void);
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_lblSide1;
extern lv_obj_t * ui_imgConnectStatus1;
extern lv_obj_t * ui_imgHousing1;
extern lv_obj_t * ui_lblGreenTime1;
extern lv_obj_t * ui_lblYellowTime1;
extern lv_obj_t * ui_lblRedTime1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

