// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#include "../ui.h"

void ui_Panel4_screen_init(void)
{
    ui_Panel4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSide4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblSide4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSide4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSide4, 0);
    lv_obj_set_y(ui_lblSide4, 5);
    lv_obj_set_align(ui_lblSide4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSide4, "SIDE-4");
    lv_obj_set_style_text_color(ui_lblSide4, lv_color_hex(0x5A7131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSide4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSide4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTime4, 80);
    lv_obj_set_y(ui_lblTime4, 0);
    lv_obj_set_align(ui_lblTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime4, "00");
    lv_obj_set_style_text_font(ui_lblTime4, &ui_font_DsDigital72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);

}
