// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef UI_PANELALLTRAFFIC_H
#define UI_PANELALLTRAFFIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PanelAllTraffic
extern void ui_PanelAllTraffic_screen_init(void);
extern void ui_PanelAllTraffic_screen_destroy(void);
extern void ui_event_PanelAllTraffic(lv_event_t * e);
extern lv_obj_t * ui_PanelAllTraffic;
extern lv_obj_t * ui_imgTrafficIntersection;
extern void ui_event_Container1(lv_event_t * e);
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_lblContainerSide1;
extern lv_obj_t * ui_imgContainerHousing1;
extern lv_obj_t * ui_lblContainerGreenTime1;
extern lv_obj_t * ui_lblContainerYellowTime1;
extern lv_obj_t * ui_lblContainerRedTime1;
extern void ui_event_Container2(lv_event_t * e);
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_lblContainerSide2;
extern lv_obj_t * ui_imgContainerHousing2;
extern lv_obj_t * ui_lblContainerGreenTime2;
extern lv_obj_t * ui_lblContainerYellowTime2;
extern lv_obj_t * ui_lblContainerRedTime2;
extern void ui_event_Container3(lv_event_t * e);
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_lblContainerSide3;
extern lv_obj_t * ui_imgContainerHousing3;
extern lv_obj_t * ui_lblContainerGreenTime3;
extern lv_obj_t * ui_lblContainerYellowTime3;
extern lv_obj_t * ui_lblContainerRedTime3;
extern void ui_event_Container4(lv_event_t * e);
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_lblContainerSide4;
extern lv_obj_t * ui_imgContainerHousing4;
extern lv_obj_t * ui_lblContainerGreenTime4;
extern lv_obj_t * ui_lblContainerYellowTime4;
extern lv_obj_t * ui_lblContainerRedTime4;
extern lv_obj_t * ui_imgConnectStatusAllTraffic;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

