// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ESP32_TrafficController

#ifndef UI_PANEL2_H
#define UI_PANEL2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Panel2
extern void ui_Panel2_screen_init(void);
extern void ui_Panel2_screen_destroy(void);
extern void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblSide2;
extern lv_obj_t * ui_imgConnectStatus2;
extern lv_obj_t * ui_imgHousing3;
extern lv_obj_t * ui_lblYellowTime2;
extern lv_obj_t * ui_lblGreenTime2;
extern lv_obj_t * ui_lblRedTime2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

